### ISSUE TITLE
Connect Shutdown Handler Raises an Exception

### ISSUE THREAD

**Issue by dixonwhitmire** [LinuxForHealth/connect#247]
Connect's shutdown handler, likely the NATS handler, throws an exception which prevents connect from closing when ctrl+c/SIGINT is sent. 

I updated the uvicorn startup params in main.py to include the lifespan setting to provide a better error message:

```python
    uvicorn_params = {
        "app": settings.uvicorn_app,
        "host": settings.uvicorn_host,
        "lifespan": "on",
        "log_config": None,
```

After starting connect, hit ctrl+c and the following exception appears

```python
2021-09-01 22:02:35,935 - connect.clients.nats - DEBUG - Subscribed tls://localhost:4222 to NATS subject EVENTS.retransmit
2021-09-01 22:02:35,949 - connect.clients.kafka - DEBUG - create_topics: created topic = LFH_SYNC
2021-09-01 22:02:35,950 - uvicorn.error - INFO - Application startup complete.
^C2021-09-01 22:05:37,899 - uvicorn.error - INFO - Shutting down
2021-09-01 22:05:38,003 - uvicorn.error - INFO - Finished server process [86433]
2021-09-01 22:05:38,003 - uvicorn.error - ERROR - Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/uvicorn/lifespan/on.py", line 84, in main
    await app(scope, self.receive, self.send)
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
    raise exc from None
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 78, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/starlette/middleware/errors.py", line 146, in __call__
    await self.app(scope, receive, send)
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/starlette/middleware/base.py", line 21, in __call__
    await self.app(scope, receive, send)
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/starlette/middleware/httpsredirect.py", line 19, in __call__
    await self.app(scope, receive, send)
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/starlette/exceptions.py", line 58, in __call__
    await self.app(scope, receive, send)
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/starlette/routing.py", line 569, in __call__
    await self.lifespan(scope, receive, send)
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/starlette/routing.py", line 544, in lifespan
    await receive()
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 58, in inner_receive
    message = await receive()
  File "/Users/tdw/.local/share/virtualenvs/connect-PVFbLzYT/lib/python3.8/site-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
asyncio.exceptions.CancelledError
```

**Comment by ccorley** [comment]
Just noting that it doesn't happen from within the debugger:
```
2021-09-01 21:14:28,944 - uvicorn.error - INFO - Application startup complete.
2021-09-01 21:14:32,572 - uvicorn.error - INFO - Shutting down
2021-09-01 21:14:32,677 - uvicorn.error - INFO - Waiting for application shutdown.
2021-09-01 21:14:32,713 - uvicorn.error - INFO - Application shutdown complete.
2021-09-01 21:14:32,714 - uvicorn.error - INFO - Finished server process [7492]

Process finished with exit code 0
```

**Comment by dixonwhitmire** [comment]
Thanks @ccorley ! Looks like this is an issue with my machine, specifically Pycharm. I am able to start via `pipenv run connect` and then ctrl+c without an issue.

```
tdw@dixons-mbp connect % pipenv run connect
Loading .env environment variables...
2021-09-01 22:30:44,762 - connect.server_handlers - INFO - Loaded logging configuration from logging.yaml
2021-09-01 22:30:44,818 - connect.clients.kafka - INFO - Created Kafka Producer
2021-09-01 22:30:44,923 - connect.clients.nats - INFO - Created NATS client
2021-09-01 22:30:44,936 - uvicorn.error - INFO - Application startup complete.
^C2021-09-01 22:30:46,385 - uvicorn.error - INFO - Shutting down
2021-09-01 22:30:46,486 - uvicorn.error - INFO - Waiting for application shutdown.
2021-09-01 22:30:46,559 - uvicorn.error - INFO - Application shutdown complete.
2021-09-01 22:30:46,559 - uvicorn.error - INFO - Finished server process [88568]
```

**Comment by ccorley** [comment]
I'm currently seeing the CancelledError with "lifespan": "on" when running from the command line.  In this case, the close_internal_clients() shutdown method is never called.  Reopening this issue to investigate.
